INSERT INTO "STATUS" VALUES
(1, 1, 'Critical'),
(2, 1, 'High'),
(3, 1, 'Medium'),
(4, 1, 'Low'),
(5, 1, 'Trivial');
INSERT INTO "COMPANY" VALUES
(6, 1, 'Health and Fitness'),
(7, 1, 'Productivity'),
(8, 1, 'Finances'),
(9, 1, 'Learning and Education'),
(10, 1, 'Relationships');   
INSERT INTO "CONTACT" VALUES
(11, 1, 'eula.lane@jigrormo.ye', 'Spend less time worrying', 'Worry-reduction', 8, 1),
(12, 1, 'barry.rodriquez@zun.mm', 'Practice time management', 'Time-management', 7, 5),
(13, 1, 'eugenia.selvi@capfad.vn', 'Reflect on daily wins', 'Reflection', 6, 3),
(14, 1, 'alejandro.miles@dec.bn', 'Invest in self-care', 'Self-care-investment', 10, 3),
(15, 1, 'cora.tesi@bivo.yt', 'Spend time with friends', 'Friendship', 6, 4),
(16, 1, 'marguerite.ishii@judbilo.gn', 'Learn a new skill', 'Skill-building', 10, 2),
(17, 1, 'mildred.jacobs@joraf.wf', 'Maintain good hygiene', 'Hygiene', 8, 1),
(18, 1, 'gene.goodman@kem.tl', 'Read inspiring books', 'Reading', 8, 5),
(19, 1, 'lettie.bennett@odeter.bb', 'Take cold showers', 'Cold-showers', 6, 1),
(20, 1, 'mabel.leach@lisohuje.vi', 'Practice daily affirmations', 'Affirmations', 10, 2),
(21, 1, 'jordan.miccinesi@duod.gy', 'Set daily intentions', 'Intention', 8, 3),
(22, 1, 'marie.parkes@nowufpus.ph', 'Simplify daily tasks', 'Simplification', 7, 1),
(23, 1, 'rose.gray@kagu.hr', 'Practice active gratitude', 'Active-gratitude', 9, 4),
(24, 1, 'garrett.stokes@fef.bg', 'Eliminate bad habits', 'Elimination', 9, 3),
(25, 1, 'barbara.matthieu@derwogi.jm', 'Wake up earlier', 'Early-rising', 7, 5),
(26, 1, 'jean.rhodes@wehovuce.gu', 'Prioritize alone time', 'Solitude', 7, 3),
(27, 1, 'jack.romoli@zamum.bw', 'Practice mindful eating', 'Mindful-eating', 6, 4),
(28, 1, 'pearl.holden@dunebuh.cr', 'Keep a clean workspace', 'Workspace', 8, 1),
(29, 1, 'belle.montero@repiwid.si', 'Regularly clean home', 'Cleaning', 9, 5),
(30, 1, 'olive.molina@razuppa.ga', 'Limit screen time', 'Screen-time', 6, 2),
(31, 1, 'minerva.todd@kulmenim.ad', 'Reduce social media use', 'Social-media', 9, 3),
(32, 1, 'bobby.pearson@ib.kg', 'Get regular check-ups', 'Check-ups', 9, 1),
(33, 1, 'larry.ciappi@ba.lk', 'Take breaks from work', 'Breaks', 10, 2),
(34, 1, 'ronnie.salucci@tohhij.lv', 'Show appreciation daily', 'Appreciation', 9, 1),
(35, 1, 'walter.grossi@tuvo.sa', 'Listen to calming music', 'Music', 9, 1);      
INSERT INTO "CONTACT" VALUES
(36, 1, 'frances.koopmans@foga.tw', 'Embrace vulnerability often', 'Vulnerability', 7, 5),
(37, 1, 'frances.fujimoto@uswuzzub.jp', 'Stretch throughout day', 'Stretching', 6, 5),
(38, 1, 'olivia.vidal@hivwerip.vc', 'Practice good posture', 'Posture', 9, 2),
(39, 1, 'edna.henry@gugusu.rw', 'Say "no" sometimes', 'Boundaries', 8, 4),
(40, 1, 'lydia.brun@zedekak.md', 'Set achievable goals', 'Goal-setting', 7, 3),
(41, 1, 'jay.blake@ral.mk', 'Declutter living space', 'Organization', 10, 4),
(42, 1, 'isabel.serafini@turuhu.bh', 'Schedule time for hobbies', 'Hobbies', 10, 1),
(43, 1, 'rebecca.carter@omjo.et', 'Reduce unnecessary spending', 'Budgeting', 8, 4),
(44, 1, 'maurice.fabbrini@rig.bh', 'Create daily to-do', 'Planning', 9, 3),
(45, 1, 'ollie.turnbull@sicewap.org', 'Regularly express gratitude', 'Thankfulness', 6, 1),
(46, 1, 'jerry.hopkins@fo.mh', 'Practice forgiveness daily', 'Forgiveness', 9, 5),
(47, 1, 'nora.lyons@gegijap.na', 'Prioritize self-care', 'Self-care', 10, 1),
(48, 1, 'anne.weis@kuvesa.pe', 'Connect with nature', 'Nature', 7, 4),
(49, 1, 'louise.gauthier@lapahu.mt', 'Kindness towards self', 'Self-kindness', 6, 2),
(50, 1, 'lloyd.fani@zev.ru', 'Mindful screen time', 'Mindfulness', 8, 1),
(51, 1, 'maud.dunn@nabeaga.ni', 'Digital detox weekends', 'Detox', 6, 1),
(52, 1, 'henry.gigli@kaot.ps', 'Active listening skills', 'Listening', 6, 5),
(53, 1, 'virgie.werner@tawuctuj.cf', 'Learn something new', 'Learning', 10, 4),
(54, 1, 'gregory.cozzi@eh.ru', 'Hydrate throughout day', 'Hydration', 8, 2),
(55, 1, 'lucinda.gil@fajjusuz.kr', 'Balanced meal planning', 'Nutrition', 7, 5),
(56, 1, 'gertrude.verbeek@pave.cc', 'Consistent sleep schedule', 'Sleep', 6, 5),
(57, 1, 'mattie.graham@ispaviw.gt', 'Mindful breathing breaks', 'Breathing', 7, 2),
(58, 1, 'bryan.shaw@ha.ee', 'Regular exercise routine', 'Exercise', 9, 1),
(59, 1, 'essie.adams@iliat.cw', 'Daily gratitude journaling', 'Gratitude', 8, 5),
(60, 1, 'gary.osborne@do.ga', 'Morning meditation practice', 'Meditation', 7, 5);