INSERT INTO "STATUS" VALUES
(1, 1, 'Critical'),
(2, 1, 'High'),
(3, 1, 'Medium'),
(4, 1, 'Low'),
(5, 1, 'Trivial');
INSERT INTO "COMPANY" VALUES
(6, 1, 'Health and Fitness'),
(7, 1, 'Productivity'),
(8, 1, 'Finances'),
(9, 1, 'Learning and Education'),
(10, 1, 'Other');  
INSERT INTO "CONTACT" VALUES
(11, 1, '', 'Spend less time worrying', 'Worry-reduction', 6, 1),
(12, 1, '', 'Practice time management', 'Time-management', 8, 5),
(13, 1, '', 'Reflect on daily wins', 'Reflection', 9, 3),
(14, 1, '', 'Invest in self-care', 'Self-care-investment', 8, 3),
(15, 1, '', 'Spend time with friends', 'Friendship', 10, 4),
(16, 1, '', 'Learn a new skill', 'Skill-building', 9, 2),
(17, 1, '', 'Maintain good hygiene', 'Hygiene', 6, 1),
(18, 1, '', 'Read inspiring books', 'Reading', 9, 5),
(19, 1, '', 'Take cold showers', 'Cold-showers', 6, 1),
(20, 1, '', 'Practice daily affirmations', 'Affirmations', 6, 2),
(21, 1, '', 'Set daily intentions', 'Intention', 7, 3),
(22, 1, '', 'Simplify daily tasks', 'Simplification', 7, 1),
(23, 1, '', 'Practice active gratitude', 'Active-gratitude', 9, 4),
(24, 1, '', 'Eliminate bad habits', 'Elimination', 7, 3),
(25, 1, '', 'Wake up earlier', 'Early-rising', 7, 5),
(26, 1, '', 'Prioritize alone time', 'Solitude', 6, 3),
(27, 1, '', 'Practice mindful eating', 'Mindful-eating', 6, 4),
(28, 1, '', 'Keep a clean workspace', 'Workspace', 10, 1),
(29, 1, '', 'Regularly clean home', 'Cleaning', 7, 5),
(30, 1, '', 'Limit screen time', 'Screen-time', 10, 2),
(31, 1, '', 'Reduce social media use', 'Social-media', 10, 3),
(32, 1, '', 'Get regular check-ups', 'Check-ups', 10, 1),
(33, 1, '', 'Take breaks from work', 'Breaks', 8, 2),
(34, 1, '', 'Show appreciation daily', 'Appreciation', 9, 1),
(35, 1, '', 'Listen to calming music', 'Music', 6, 1);      
INSERT INTO "CONTACT" VALUES
(36, 1, '', 'Embrace vulnerability often', 'Vulnerability', 9, 5),
(37, 1, '', 'Stretch throughout day', 'Stretching', 6, 5),
(38, 1, '', 'Practice good posture', 'Posture', 6, 2),
(39, 1, '', 'Say "no" sometimes', 'Boundaries', 10, 4),
(40, 1, '', 'Set achievable goals', 'Goal-setting', 7, 3),
(41, 1, '', 'Declutter living space', 'Organization', 7, 4),
(42, 1, '', 'Schedule time for hobbies', 'Hobbies', 7, 1),
(43, 1, '', 'Reduce unnecessary spending', 'Budgeting', 8, 4),
(44, 1, '', 'Create daily to-do', 'Planning', 7, 3),
(45, 1, '', 'Regularly express gratitude', 'Thankfulness', 10, 1),
(46, 1, '', 'Practice forgiveness daily', 'Forgiveness', 10, 5),
(47, 1, '', 'Prioritize self-care', 'Self-care', 6, 1),
(48, 1, '', 'Connect with nature', 'Nature', 6, 4),
(49, 1, '', 'Kindness towards self', 'Self-kindness', 6, 2),
(50, 1, '', 'Mindful screen time', 'Mindfulness', 10, 1),
(51, 1, '', 'Digital detox weekends', 'Detox', 7, 1),
(52, 1, '', 'Active listening skills', 'Listening', 10, 5),
(53, 1, '', 'Learn something new', 'Learning', 9, 4),
(54, 1, '', 'Hydrate throughout day', 'Hydration', 6, 2),
(55, 1, '', 'Balanced meal planning', 'Nutrition', 6, 5),
(56, 1, '', 'Consistent sleep schedule', 'Sleep', 6, 5),
(57, 1, '', 'Mindful breathing breaks', 'Breathing', 6, 2),
(58, 1, '', 'Regular exercise routine', 'Exercise', 6, 1),
(59, 1, '', 'Daily gratitude journaling', 'Gratitude', 9, 5),
(60, 1, '', 'Morning meditation practice', 'Meditation', 9, 5);